//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IControlCalibration2Raw : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IControlCalibration2Raw(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IControlCalibration2Raw obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IControlCalibration2Raw() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_IControlCalibration2Raw(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual bool calibrate2Raw(int axis, uint type, double p1, double p2, double p3) {
    bool ret = yarpPINVOKE.IControlCalibration2Raw_calibrate2Raw(swigCPtr, axis, type, p1, p2, p3);
    return ret;
  }

  public virtual bool setCalibrationParametersRaw(int axis, CalibrationParameters arg1) {
    bool ret = yarpPINVOKE.IControlCalibration2Raw_setCalibrationParametersRaw(swigCPtr, axis, CalibrationParameters.getCPtr(arg1));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool doneRaw(int j) {
    bool ret = yarpPINVOKE.IControlCalibration2Raw_doneRaw(swigCPtr, j);
    return ret;
  }

}
