//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IControlCalibration : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IControlCalibration(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IControlCalibration obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IControlCalibration() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_IControlCalibration(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual bool calibrate(int j, double p) {
    bool ret = yarpPINVOKE.IControlCalibration_calibrate__SWIG_0(swigCPtr, j, p);
    return ret;
  }

  public virtual bool done(int j) {
    bool ret = yarpPINVOKE.IControlCalibration_done(swigCPtr, j);
    return ret;
  }

  public virtual bool setCalibrator(SWIGTYPE_p_ICalibrator c) {
    bool ret = yarpPINVOKE.IControlCalibration_setCalibrator(swigCPtr, SWIGTYPE_p_ICalibrator.getCPtr(c));
    return ret;
  }

  public virtual bool calibrate() {
    bool ret = yarpPINVOKE.IControlCalibration_calibrate__SWIG_1(swigCPtr);
    return ret;
  }

  public virtual bool park(bool wait) {
    bool ret = yarpPINVOKE.IControlCalibration_park__SWIG_0(swigCPtr, wait);
    return ret;
  }

  public virtual bool park() {
    bool ret = yarpPINVOKE.IControlCalibration_park__SWIG_1(swigCPtr);
    return ret;
  }

}
