//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum JointTypeEnum {
  VOCAB_JOINTTYPE_REVOLUTE = '((((int) ((v))) << 24) +(((int) ((r))) << 16) +(((int) ((t))) << 8) +((int) ((a))))',
  VOCAB_JOINTTYPE_PRISMATIC = '((((int) ((r))) << 24) +(((int) ((p))) << 16) +(((int) ((t))) << 8) +((int) ((a))))',
  VOCAB_JOINTTYPE_UNKNOWN = '((((int) ((n))) << 24) +(((int) ((k))) << 16) +(((int) ((n))) << 8) +((int) ((u))))'
}
