//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum YarpVocabPixelTypesEnum {
  VOCAB_PIXEL_INVALID = 0,
  VOCAB_PIXEL_MONO = '((((int) ((o))) << 24) +(((int) ((n))) << 16) +(((int) ((o))) << 8) +((int) ((m))))',
  VOCAB_PIXEL_MONO16 = '((((int) ((6))) << 24) +(((int) ((1))) << 16) +(((int) ((o))) << 8) +((int) ((m))))',
  VOCAB_PIXEL_RGB = '((((int) ((0))) << 24) +(((int) ((b))) << 16) +(((int) ((g))) << 8) +((int) ((r))))',
  VOCAB_PIXEL_RGBA = '((((int) ((a))) << 24) +(((int) ((b))) << 16) +(((int) ((g))) << 8) +((int) ((r))))',
  VOCAB_PIXEL_BGRA = ((((int) ((a))) << 24) +(((int) ((r))) << 16) +(((int) ((g))) << 8) +((int) ((98)))),
  VOCAB_PIXEL_INT = '((((int) ((0))) << 24) +(((int) ((t))) << 16) +(((int) ((n))) << 8) +((int) ((i))))',
  VOCAB_PIXEL_HSV = '((((int) ((0))) << 24) +(((int) ((v))) << 16) +(((int) ((s))) << 8) +((int) ((h))))',
  VOCAB_PIXEL_BGR = ((((int) ((0))) << 24) +(((int) ((r))) << 16) +(((int) ((g))) << 8) +((int) ((98)))),
  VOCAB_PIXEL_MONO_SIGNED = '((((int) ((n))) << 24) +(((int) ((g))) << 16) +(((int) ((i))) << 8) +((int) ((s))))',
  VOCAB_PIXEL_RGB_SIGNED = '((((int) ((-))) << 24) +(((int) ((b))) << 16) +(((int) ((g))) << 8) +((int) ((r))))',
  VOCAB_PIXEL_RGB_INT = '((((int) ((i))) << 24) +(((int) ((b))) << 16) +(((int) ((g))) << 8) +((int) ((r))))',
  VOCAB_PIXEL_MONO_FLOAT = '((((int) ((0))) << 24) +(((int) ((c))) << 16) +(((int) ((e))) << 8) +((int) (((0)))))',
  VOCAB_PIXEL_RGB_FLOAT = '((((int) ((.))) << 24) +(((int) ((b))) << 16) +(((int) ((g))) << 8) +((int) ((r))))',
  VOCAB_PIXEL_HSV_FLOAT = '((((int) ((.))) << 24) +(((int) ((v))) << 16) +(((int) ((s))) << 8) +((int) ((h))))',
  VOCAB_PIXEL_ENCODING_BAYER_GRBG8 = '((((int) ((g))) << 24) +(((int) ((b))) << 16) +(((int) ((r))) << 8) +((int) ((g))))',
  VOCAB_PIXEL_ENCODING_BAYER_GRBG16 = '((((int) ((6))) << 24) +(((int) ((1))) << 16) +(((int) ((r))) << 8) +((int) ((g))))',
  VOCAB_PIXEL_ENCODING_BAYER_BGGR8 = ((((int) ((r))) << 24) +(((int) ((g))) << 16) +(((int) ((g))) << 8) +((int) ((98)))),
  VOCAB_PIXEL_ENCODING_BAYER_BGGR16 = ((((int) ((6))) << 24) +(((int) ((1))) << 16) +(((int) ((g))) << 8) +((int) ((98)))),
  VOCAB_PIXEL_ENCODING_BAYER_GBRG8 = '((((int) ((g))) << 24) +(((int) ((r))) << 16) +(((int) ((b))) << 8) +((int) ((g))))',
  VOCAB_PIXEL_ENCODING_BAYER_GBRG16 = '((((int) ((6))) << 24) +(((int) ((1))) << 16) +(((int) ((b))) << 8) +((int) ((g))))',
  VOCAB_PIXEL_ENCODING_BAYER_RGGB8 = '-((((int) ((b))) << 24) +(((int) ((g))) << 16) +(((int) ((g))) << 8) +((int) ((r))))',
  VOCAB_PIXEL_ENCODING_BAYER_RGGB16 = '((((int) ((6))) << 24) +(((int) ((1))) << 16) +(((int) ((g))) << 8) +((int) ((r))))'
}
