/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class ImageMono : Image {
  private HandleRef swigCPtr;

  internal ImageMono(IntPtr cPtr, bool cMemoryOwn) : base(yarpPINVOKE.ImageMono_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ImageMono obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ImageMono() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_ImageMono(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public override int getPixelSize() {
    int ret = yarpPINVOKE.ImageMono_getPixelSize(swigCPtr);
    return ret;
  }

  public override int getPixelCode() {
    int ret = yarpPINVOKE.ImageMono_getPixelCode(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_unsigned_char pixel(int x, int y) {
    SWIGTYPE_p_unsigned_char ret = new SWIGTYPE_p_unsigned_char(yarpPINVOKE.ImageMono_pixel(swigCPtr, x, y), false);
    return ret;
  }

  public SWIGTYPE_p_unsigned_char access(int x, int y) {
    SWIGTYPE_p_unsigned_char ret = new SWIGTYPE_p_unsigned_char(yarpPINVOKE.ImageMono_access(swigCPtr, x, y), false);
    return ret;
  }

  public SWIGTYPE_p_unsigned_char safePixel(int x, int y) {
    SWIGTYPE_p_unsigned_char ret = new SWIGTYPE_p_unsigned_char(yarpPINVOKE.ImageMono_safePixel__SWIG_0(swigCPtr, x, y), false);
    return ret;
  }

  public ImageMono() : this(yarpPINVOKE.new_ImageMono(), true) {
  }

}
