/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class PortWriterWrapper : PortWriter {
  private HandleRef swigCPtr;

  internal PortWriterWrapper(IntPtr cPtr, bool cMemoryOwn) : base(yarpPINVOKE.PortWriterWrapper_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PortWriterWrapper obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PortWriterWrapper() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_PortWriterWrapper(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public virtual PortWriter getInternal() {
    IntPtr cPtr = yarpPINVOKE.PortWriterWrapper_getInternal(swigCPtr);
    PortWriter ret = (cPtr == IntPtr.Zero) ? null : new PortWriter(cPtr, false);
    return ret;
  }

}
