/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class TypedReaderImageInt : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TypedReaderImageInt(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TypedReaderImageInt obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TypedReaderImageInt() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_TypedReaderImageInt(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public new void setStrict(bool strict) {
    yarpPINVOKE.TypedReaderImageInt_setStrict__SWIG_0(swigCPtr, strict);
  }

  public new void setStrict() {
    yarpPINVOKE.TypedReaderImageInt_setStrict__SWIG_1(swigCPtr);
  }

  public new ImageInt read(bool shouldWait) {
    IntPtr cPtr = yarpPINVOKE.TypedReaderImageInt_read__SWIG_0(swigCPtr, shouldWait);
    ImageInt ret = (cPtr == IntPtr.Zero) ? null : new ImageInt(cPtr, false);
    return ret;
  }

  public new ImageInt read() {
    IntPtr cPtr = yarpPINVOKE.TypedReaderImageInt_read__SWIG_1(swigCPtr);
    ImageInt ret = (cPtr == IntPtr.Zero) ? null : new ImageInt(cPtr, false);
    return ret;
  }

  public virtual void interrupt() {
    yarpPINVOKE.TypedReaderImageInt_interrupt(swigCPtr);
  }

  public new ImageInt lastRead() {
    IntPtr cPtr = yarpPINVOKE.TypedReaderImageInt_lastRead(swigCPtr);
    ImageInt ret = (cPtr == IntPtr.Zero) ? null : new ImageInt(cPtr, false);
    return ret;
  }

  public new bool isClosed() {
    bool ret = yarpPINVOKE.TypedReaderImageInt_isClosed(swigCPtr);
    return ret;
  }

  public new void useCallback(TypedReaderCallbackImageInt callback) {
    yarpPINVOKE.TypedReaderImageInt_useCallback(swigCPtr, TypedReaderCallbackImageInt.getCPtr(callback));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void disableCallback() {
    yarpPINVOKE.TypedReaderImageInt_disableCallback(swigCPtr);
  }

  public new int getPendingReads() {
    int ret = yarpPINVOKE.TypedReaderImageInt_getPendingReads(swigCPtr);
    return ret;
  }

  public virtual string getName() {
    string ret = yarpPINVOKE.TypedReaderImageInt_getName(swigCPtr);
    return ret;
  }

  public new void setReplier(PortReader reader) {
    yarpPINVOKE.TypedReaderImageInt_setReplier(swigCPtr, PortReader.getCPtr(reader));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual System.IntPtr acquire() { return yarpPINVOKE.TypedReaderImageInt_acquire(swigCPtr); }

  public virtual void release(System.IntPtr handle) {
    yarpPINVOKE.TypedReaderImageInt_release(swigCPtr, handle);
  }

  public new void setTargetPeriod(double period) {
    yarpPINVOKE.TypedReaderImageInt_setTargetPeriod(swigCPtr, period);
  }

}
