//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IControlMode : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IControlMode(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IControlMode obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IControlMode() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_IControlMode(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual bool setPositionMode(int j) {
    bool ret = yarpPINVOKE.IControlMode_setPositionMode(swigCPtr, j);
    return ret;
  }

  public virtual bool setVelocityMode(int j) {
    bool ret = yarpPINVOKE.IControlMode_setVelocityMode(swigCPtr, j);
    return ret;
  }

  public virtual bool setTorqueMode(int j) {
    bool ret = yarpPINVOKE.IControlMode_setTorqueMode(swigCPtr, j);
    return ret;
  }

  public virtual bool setImpedancePositionMode(int j) {
    bool ret = yarpPINVOKE.IControlMode_setImpedancePositionMode(swigCPtr, j);
    return ret;
  }

  public virtual bool setImpedanceVelocityMode(int j) {
    bool ret = yarpPINVOKE.IControlMode_setImpedanceVelocityMode(swigCPtr, j);
    return ret;
  }

  public virtual bool setOpenLoopMode(int j) {
    bool ret = yarpPINVOKE.IControlMode_setOpenLoopMode(swigCPtr, j);
    return ret;
  }

  public virtual bool getControlMode(int j, SWIGTYPE_p_int mode) {
    bool ret = yarpPINVOKE.IControlMode_getControlMode(swigCPtr, j, SWIGTYPE_p_int.getCPtr(mode));
    return ret;
  }

  public virtual bool getControlModes(SWIGTYPE_p_int modes) {
    bool ret = yarpPINVOKE.IControlMode_getControlModes(swigCPtr, SWIGTYPE_p_int.getCPtr(modes));
    return ret;
  }

}
