/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class BottleCallback : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BottleCallback(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(BottleCallback obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~BottleCallback() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_BottleCallback(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public new void onRead(Bottle datum) {
    if (SwigDerivedClassHasMethod("onRead", swigMethodTypes0)) yarpPINVOKE.BottleCallback_onReadSwigExplicitBottleCallback__SWIG_0(swigCPtr, Bottle.getCPtr(datum)); else yarpPINVOKE.BottleCallback_onRead__SWIG_0(swigCPtr, Bottle.getCPtr(datum));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public new void onRead(Bottle datum, TypedReaderBottle reader) {
    if (SwigDerivedClassHasMethod("onRead", swigMethodTypes1)) yarpPINVOKE.BottleCallback_onReadSwigExplicitBottleCallback__SWIG_1(swigCPtr, Bottle.getCPtr(datum), TypedReaderBottle.getCPtr(reader)); else yarpPINVOKE.BottleCallback_onRead__SWIG_1(swigCPtr, Bottle.getCPtr(datum), TypedReaderBottle.getCPtr(reader));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public BottleCallback() : this(yarpPINVOKE.new_BottleCallback(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("onRead", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateBottleCallback_0(SwigDirectoronRead__SWIG_0);
    if (SwigDerivedClassHasMethod("onRead", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateBottleCallback_1(SwigDirectoronRead__SWIG_1);
    yarpPINVOKE.BottleCallback_director_connect(swigCPtr, swigDelegate0, swigDelegate1);
  }

  private bool SwigDerivedClassHasMethod(string methodName, Type[] methodTypes) {
    System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(BottleCallback));
    return hasDerivedMethod;
  }

  private void SwigDirectoronRead__SWIG_0(IntPtr datum) {
    onRead(new Bottle(datum, false));
  }

  private void SwigDirectoronRead__SWIG_1(IntPtr datum, IntPtr reader) {
    onRead(new Bottle(datum, false), new TypedReaderBottle(reader, false));
  }

  public delegate void SwigDelegateBottleCallback_0(IntPtr datum);
  public delegate void SwigDelegateBottleCallback_1(IntPtr datum, IntPtr reader);

  private SwigDelegateBottleCallback_0 swigDelegate0;
  private SwigDelegateBottleCallback_1 swigDelegate1;

  private static Type[] swigMethodTypes0 = new Type[] { typeof(Bottle) };
  private static Type[] swigMethodTypes1 = new Type[] { typeof(Bottle), typeof(TypedReaderBottle) };
}
