/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class DummyConnector : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DummyConnector(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DummyConnector obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DummyConnector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_DummyConnector(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public DummyConnector() : this(yarpPINVOKE.new_DummyConnector(), true) {
  }

  public void setTextMode(bool textmode) {
    yarpPINVOKE.DummyConnector_setTextMode(swigCPtr, textmode);
  }

  public ConnectionWriter getCleanWriter() {
    ConnectionWriter ret = new ConnectionWriter(yarpPINVOKE.DummyConnector_getCleanWriter(swigCPtr), false);
    return ret;
  }

  public ConnectionWriter getWriter() {
    ConnectionWriter ret = new ConnectionWriter(yarpPINVOKE.DummyConnector_getWriter(swigCPtr), false);
    return ret;
  }

  public ConnectionReader getReader() {
    ConnectionReader ret = new ConnectionReader(yarpPINVOKE.DummyConnector_getReader(swigCPtr), false);
    return ret;
  }

  public void reset() {
    yarpPINVOKE.DummyConnector_reset(swigCPtr);
  }

}
