/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class FlexImage : Image {
  private HandleRef swigCPtr;

  internal FlexImage(IntPtr cPtr, bool cMemoryOwn) : base(yarpPINVOKE.FlexImage_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(FlexImage obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~FlexImage() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_FlexImage(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public void setPixelCode(int imgPixelCode) {
    yarpPINVOKE.FlexImage_setPixelCode(swigCPtr, imgPixelCode);
  }

  public void setPixelSize(int imgPixelSize) {
    yarpPINVOKE.FlexImage_setPixelSize(swigCPtr, imgPixelSize);
  }

  public new void setQuantum(int imgQuantum) {
    yarpPINVOKE.FlexImage_setQuantum(swigCPtr, imgQuantum);
  }

  public FlexImage() : this(yarpPINVOKE.new_FlexImage(), true) {
  }

}
