/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class IControlCalibration2 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IControlCalibration2(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(IControlCalibration2 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~IControlCalibration2() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_IControlCalibration2(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public virtual bool calibrate2(int axis, uint type, double p1, double p2, double p3) {
    bool ret = yarpPINVOKE.IControlCalibration2_calibrate2(swigCPtr, axis, type, p1, p2, p3);
    return ret;
  }

  public virtual bool setCalibrationParameters(int axis, CalibrationParameters arg1) {
    bool ret = yarpPINVOKE.IControlCalibration2_setCalibrationParameters(swigCPtr, axis, CalibrationParameters.getCPtr(arg1));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool done(int j) {
    bool ret = yarpPINVOKE.IControlCalibration2_done(swigCPtr, j);
    return ret;
  }

  public virtual bool setCalibrator(SWIGTYPE_p_ICalibrator c) {
    bool ret = yarpPINVOKE.IControlCalibration2_setCalibrator(swigCPtr, SWIGTYPE_p_ICalibrator.getCPtr(c));
    return ret;
  }

  public virtual bool calibrate() {
    bool ret = yarpPINVOKE.IControlCalibration2_calibrate(swigCPtr);
    return ret;
  }

  public virtual bool park(bool wait) {
    bool ret = yarpPINVOKE.IControlCalibration2_park__SWIG_0(swigCPtr, wait);
    return ret;
  }

  public virtual bool park() {
    bool ret = yarpPINVOKE.IControlCalibration2_park__SWIG_1(swigCPtr);
    return ret;
  }

  public virtual bool abortCalibration() {
    bool ret = yarpPINVOKE.IControlCalibration2_abortCalibration(swigCPtr);
    return ret;
  }

  public virtual bool abortPark() {
    bool ret = yarpPINVOKE.IControlCalibration2_abortPark(swigCPtr);
    return ret;
  }

}
