/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class ImageInt : Image {
  private HandleRef swigCPtr;

  internal ImageInt(IntPtr cPtr, bool cMemoryOwn) : base(yarpPINVOKE.ImageInt_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ImageInt obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ImageInt() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_ImageInt(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public override int getPixelSize() {
    int ret = yarpPINVOKE.ImageInt_getPixelSize(swigCPtr);
    return ret;
  }

  public override int getPixelCode() {
    int ret = yarpPINVOKE.ImageInt_getPixelCode(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_int pixel(int x, int y) {
    SWIGTYPE_p_int ret = new SWIGTYPE_p_int(yarpPINVOKE.ImageInt_pixel(swigCPtr, x, y), false);
    return ret;
  }

  public SWIGTYPE_p_int access(int x, int y) {
    SWIGTYPE_p_int ret = new SWIGTYPE_p_int(yarpPINVOKE.ImageInt_access(swigCPtr, x, y), false);
    return ret;
  }

  public SWIGTYPE_p_int safePixel(int x, int y) {
    SWIGTYPE_p_int ret = new SWIGTYPE_p_int(yarpPINVOKE.ImageInt_safePixel__SWIG_0(swigCPtr, x, y), false);
    return ret;
  }

  public int getPixel(int x, int y) {
    int ret = yarpPINVOKE.ImageInt_getPixel(swigCPtr, x, y);
    return ret;
  }

  public void setPixel(int x, int y, int v) {
    yarpPINVOKE.ImageInt_setPixel(swigCPtr, x, y, v);
  }

  public ImageInt() : this(yarpPINVOKE.new_ImageInt(), true) {
  }

}
