/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class ImageRgb : Image {
  private HandleRef swigCPtr;

  internal ImageRgb(IntPtr cPtr, bool cMemoryOwn) : base(yarpPINVOKE.ImageRgb_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ImageRgb obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ImageRgb() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_ImageRgb(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public override int getPixelSize() {
    int ret = yarpPINVOKE.ImageRgb_getPixelSize(swigCPtr);
    return ret;
  }

  public override int getPixelCode() {
    int ret = yarpPINVOKE.ImageRgb_getPixelCode(swigCPtr);
    return ret;
  }

  public PixelRgb pixel(int x, int y) {
    PixelRgb ret = new PixelRgb(yarpPINVOKE.ImageRgb_pixel(swigCPtr, x, y), false);
    return ret;
  }

  public PixelRgb access(int x, int y) {
    PixelRgb ret = new PixelRgb(yarpPINVOKE.ImageRgb_access(swigCPtr, x, y), false);
    return ret;
  }

  public PixelRgb safePixel(int x, int y) {
    PixelRgb ret = new PixelRgb(yarpPINVOKE.ImageRgb_safePixel__SWIG_0(swigCPtr, x, y), false);
    return ret;
  }

  public ImageRgb() : this(yarpPINVOKE.new_ImageRgb(), true) {
  }

}
