/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class IOpenLoopControlRaw : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IOpenLoopControlRaw(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(IOpenLoopControlRaw obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~IOpenLoopControlRaw() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_IOpenLoopControlRaw(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public virtual bool setRefOutputRaw(int j, double v) {
    bool ret = yarpPINVOKE.IOpenLoopControlRaw_setRefOutputRaw(swigCPtr, j, v);
    return ret;
  }

  public virtual bool setRefOutputsRaw(SWIGTYPE_p_double v) {
    bool ret = yarpPINVOKE.IOpenLoopControlRaw_setRefOutputsRaw(swigCPtr, SWIGTYPE_p_double.getCPtr(v));
    return ret;
  }

  public virtual bool getRefOutputRaw(int j, SWIGTYPE_p_double v) {
    bool ret = yarpPINVOKE.IOpenLoopControlRaw_getRefOutputRaw(swigCPtr, j, SWIGTYPE_p_double.getCPtr(v));
    return ret;
  }

  public virtual bool getRefOutputsRaw(SWIGTYPE_p_double v) {
    bool ret = yarpPINVOKE.IOpenLoopControlRaw_getRefOutputsRaw(swigCPtr, SWIGTYPE_p_double.getCPtr(v));
    return ret;
  }

  public virtual bool getOutputRaw(int j, SWIGTYPE_p_double v) {
    bool ret = yarpPINVOKE.IOpenLoopControlRaw_getOutputRaw(swigCPtr, j, SWIGTYPE_p_double.getCPtr(v));
    return ret;
  }

  public virtual bool getOutputsRaw(SWIGTYPE_p_double v) {
    bool ret = yarpPINVOKE.IOpenLoopControlRaw_getOutputsRaw(swigCPtr, SWIGTYPE_p_double.getCPtr(v));
    return ret;
  }

  public virtual bool setOpenLoopModeRaw() {
    bool ret = yarpPINVOKE.IOpenLoopControlRaw_setOpenLoopModeRaw(swigCPtr);
    return ret;
  }

}
