//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum JointTypeEnum {
  VOCAB_JOINTTYPE_REVOLUTE = 0,
  VOCAB_JOINTTYPE_PRISMATIC = 0,
  VOCAB_JOINTTYPE_UNKNOWN = 0
}
