/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class MotorTorqueParameters : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MotorTorqueParameters(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(MotorTorqueParameters obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~MotorTorqueParameters() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_MotorTorqueParameters(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public double bemf {
    set {
      yarpPINVOKE.MotorTorqueParameters_bemf_set(swigCPtr, value);
    } 
    get {
      double ret = yarpPINVOKE.MotorTorqueParameters_bemf_get(swigCPtr);
      return ret;
    } 
  }

  public double bemf_scale {
    set {
      yarpPINVOKE.MotorTorqueParameters_bemf_scale_set(swigCPtr, value);
    } 
    get {
      double ret = yarpPINVOKE.MotorTorqueParameters_bemf_scale_get(swigCPtr);
      return ret;
    } 
  }

  public double ktau {
    set {
      yarpPINVOKE.MotorTorqueParameters_ktau_set(swigCPtr, value);
    } 
    get {
      double ret = yarpPINVOKE.MotorTorqueParameters_ktau_get(swigCPtr);
      return ret;
    } 
  }

  public double ktau_scale {
    set {
      yarpPINVOKE.MotorTorqueParameters_ktau_scale_set(swigCPtr, value);
    } 
    get {
      double ret = yarpPINVOKE.MotorTorqueParameters_ktau_scale_get(swigCPtr);
      return ret;
    } 
  }

  public MotorTorqueParameters() : this(yarpPINVOKE.new_MotorTorqueParameters(), true) {
  }

}
