/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class PixelRgb : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PixelRgb(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PixelRgb obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PixelRgb() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_PixelRgb(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public byte r {
    set {
      yarpPINVOKE.PixelRgb_r_set(swigCPtr, value);
    } 
    get {
      byte ret = yarpPINVOKE.PixelRgb_r_get(swigCPtr);
      return ret;
    } 
  }

  public byte g {
    set {
      yarpPINVOKE.PixelRgb_g_set(swigCPtr, value);
    } 
    get {
      byte ret = yarpPINVOKE.PixelRgb_g_get(swigCPtr);
      return ret;
    } 
  }

  public byte b {
    set {
      yarpPINVOKE.PixelRgb_b_set(swigCPtr, value);
    } 
    get {
      byte ret = yarpPINVOKE.PixelRgb_b_get(swigCPtr);
      return ret;
    } 
  }

  public PixelRgb() : this(yarpPINVOKE.new_PixelRgb__SWIG_0(), true) {
  }

  public PixelRgb(byte n_r, byte n_g, byte n_b) : this(yarpPINVOKE.new_PixelRgb__SWIG_1(n_r, n_g, n_b), true) {
  }

}
