/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class PixelRgba : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PixelRgba(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PixelRgba obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PixelRgba() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_PixelRgba(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public byte r {
    set {
      yarpPINVOKE.PixelRgba_r_set(swigCPtr, value);
    } 
    get {
      byte ret = yarpPINVOKE.PixelRgba_r_get(swigCPtr);
      return ret;
    } 
  }

  public byte g {
    set {
      yarpPINVOKE.PixelRgba_g_set(swigCPtr, value);
    } 
    get {
      byte ret = yarpPINVOKE.PixelRgba_g_get(swigCPtr);
      return ret;
    } 
  }

  public byte b {
    set {
      yarpPINVOKE.PixelRgba_b_set(swigCPtr, value);
    } 
    get {
      byte ret = yarpPINVOKE.PixelRgba_b_get(swigCPtr);
      return ret;
    } 
  }

  public byte a {
    set {
      yarpPINVOKE.PixelRgba_a_set(swigCPtr, value);
    } 
    get {
      byte ret = yarpPINVOKE.PixelRgba_a_get(swigCPtr);
      return ret;
    } 
  }

  public PixelRgba() : this(yarpPINVOKE.new_PixelRgba__SWIG_0(), true) {
  }

  public PixelRgba(byte n_r, byte n_g, byte n_b, byte n_a) : this(yarpPINVOKE.new_PixelRgba__SWIG_1(n_r, n_g, n_b, n_a), true) {
  }

}
