//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum YarpVocabPixelTypesEnum {
  	VOCAB_PIXEL_INVALID = 0,
	VOCAB_PIXEL_MONO = 0,
	VOCAB_PIXEL_MONO16 = 0,
	VOCAB_PIXEL_RGB = 0,
	VOCAB_PIXEL_RGBA = 0,
	VOCAB_PIXEL_BGRA = 0,
	VOCAB_PIXEL_INT = 0,
	VOCAB_PIXEL_HSV = 0,
	VOCAB_PIXEL_BGR = 0,
	VOCAB_PIXEL_MONO_SIGNED = 0,
	VOCAB_PIXEL_RGB_SIGNED = 0,
	VOCAB_PIXEL_RGB_INT = 0,
	VOCAB_PIXEL_MONO_FLOAT = 0,
	VOCAB_PIXEL_RGB_FLOAT = 0,
	VOCAB_PIXEL_HSV_FLOAT = 0,
  VOCAB_PIXEL_ENCODING_BAYER_GRBG8 = 0,
  VOCAB_PIXEL_ENCODING_BAYER_GRBG16 =0,
  VOCAB_PIXEL_ENCODING_BAYER_BGGR8 = 0,
  VOCAB_PIXEL_ENCODING_BAYER_BGGR16 = 0,
  VOCAB_PIXEL_ENCODING_BAYER_GBRG8 = 0,
  VOCAB_PIXEL_ENCODING_BAYER_GBRG16 = 0,
  VOCAB_PIXEL_ENCODING_BAYER_RGGB8 =0,
  VOCAB_PIXEL_ENCODING_BAYER_RGGB16 = 0
}
